// src/types/dreamAnalysis.ts

import { z } from 'zod';

// Type representing the analysis details stored in our separate tables.
export interface DreamAnalysis {
  // Core dream info from dream_entries
  dream_entry: {
    id: number;
    title: string;
    content: string; // original dream text
    created_at?: string;
    updated_at?: string;
    summary?: string;
    image_url?: string;
  };
  // Analysis stored in dream_analysis and supporting_points
  analysis: {
    tags: {
      bible: string;
      language: string;
      bible_book: string;
      general_theme: string[];
    };
    topic_sentence: string;
    supporting_points: Array<{
      point: string;
      citation: string;
      bible_quote: string;
      additional: string;
    }>;
  };
}

// Zod schema to validate the analysis object received from ChatGPT or inserted via an API.
// Note: This schema reflects the structure of the analysis part only.
export const dreamAnalysisSchema = z.object({
  title: z.string(), // a short title for the analysis
  original_dream: z.string(), // corresponds to dream_entries.content
  tags: z.object({
    bible: z.string(),
    language: z.string(),
    bible_book: z.string(),
    general_theme: z.array(z.string()),
  }),
  analysis: z.object({
    topic_sentence: z.string(),
    supporting_points: z.array(
      z.object({
        point: z.string(),
        citation: z.string(),
        bible_quote: z.string(),
        additional: z.string(),
      })
    ),
  }),
  // Timestamps are auto-generated by Supabase, so they are optional
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});